/**
 * TypeScript bridge to the core UniFFI native module.
 *
 * The native module (generated by UniFFI) is loaded as 'gardens_core' via the
 * React Native TurboModule / JSI bridge.  During unit tests or web preview
 * we fall back to a JS stub so the module can be imported without crashing.
 */

import { NativeModules, TurboModuleRegistry } from 'react-native';

export interface KeyPair {
  privateKeyHex: string; // 64 hex chars — Ed25519 private key seed
  publicKeyHex: string;  // 64 hex chars — peer identity
  mnemonic: string;      // 24 space-separated BIP-39 words
}

export class KeyError extends Error {
  constructor(
    public readonly kind: 'InvalidMnemonic' | 'InvalidPrivateKey',
    message: string,
  ) {
    super(message);
    this.name = 'KeyError';
  }
}

// ── Phase 3 types ──────────────────────────────────────────────────────────────

export type ConnectionStatus = 'Online' | 'Connecting' | 'Offline';

// ── Data types ────────────────────────────────────────────────────────────────

export interface Profile {
  publicKey: string;
  username: string;
  avatarBlobId: string | null;
  bio: string | null;
  availableFor: string[];
  isPublic: boolean;
  emailEnabled?: boolean;
  createdAt: number;
  updatedAt: number;
}

export interface PkarrResolved {
  recordType: string;
  name: string | null;
  username: string | null;
  description: string | null;
  bio: string | null;
  avatarBlobId: string | null;
  coverBlobId: string | null;
  publicKey: string;
  email: boolean;
}

export interface OnionHopFfi {
  pubkeyHex: string;
  nextUrl: string;
}


export interface OnionPeeled {
  peelType: 'forward' | 'deliver';
  nextHopUrl: string | null;
  innerPacket: Uint8Array | null;
  topicId: Uint8Array | null;
  op: Uint8Array | null;
}

export interface OrgSummary {
  orgId: string;
  name: string;
  typeLabel: string;
  description: string | null;
  avatarBlobId: string | null;
  coverBlobId: string | null;
  welcomeText: string | null;
  customEmojiJson: string | null;
  orgCooldownSecs: number | null;
  isPublic: boolean;
  emailEnabled?: boolean;
  creatorKey: string;
  orgPubkey: string | null;  // Org's z32-encoded public key for pkarr
  createdAt: number;
}

export interface Room {
  roomId: string;
  orgId: string;
  name: string;
  createdBy: string;
  createdAt: number;
  encKeyEpoch: number;
  isArchived: boolean;
  archivedAt: number | null;
  roomCooldownSecs: number | null;
}

export interface Event {
  eventId: string;
  orgId: string;
  title: string;
  description: string | null;
  locationType: string;
  locationText: string | null;
  locationRoomId: string | null;
  startAt: number;
  endAt: number | null;
  createdBy: string;
  createdAt: number;
  isDeleted: boolean;
}

export interface EventRsvp {
  eventId: string;
  memberKey: string;
  status: string;
  updatedAt: number;
}

export interface IceInfo {
  publicKey: string;
  icedUntil: number;
}

export interface Message {
  messageId: string;
  roomId: string | null;
  dmThreadId: string | null;
  authorKey: string;
  contentType: string;
  textContent: string | null;
  blobId: string | null;
  embedUrl: string | null;
  mentions: string[];
  replyTo: string | null;
  timestamp: number;
  editedAt: number | null;
  isDeleted: boolean;
}

export interface Reaction {
  messageId: string;
  emoji: string;
  reactorKey: string;
}

export interface DmThread {
  threadId: string;
  initiatorKey: string;
  recipientKey: string;
  createdAt: number;
  lastMessageAt: number | null;
  isRequest: boolean;
}

/** Returned by sendMessage and createDmThread. op_bytes must be forwarded via onion routing. */
export interface SendResult {
  /** message_id or thread_id (op hash hex) */
  id: string;
  /** GossipEnvelope CBOR bytes (if you need to forward or store externally) */
  opBytes: Uint8Array;
}

// ── Phase 5 types ──────────────────────────────────────────────────────────────

export class AuthError extends Error {
  constructor(
    public readonly kind: 'InvalidSignature' | 'TokenExpired' | 'Unauthorized' | 'NotInitialised',
    message: string,
  ) {
    super(message);
    this.name = 'AuthError';
  }
}

export interface InviteTokenInfo {
  orgId: string;
  inviterKey: string;
  accessLevel: string;
  expiryTimestamp: number;
}

export interface MemberInfo {
  publicKey: string;
  accessLevel: string;
  joinedAt: number;
}

// ── Native module interface ───────────────────────────────────────────────────

interface GardensCoreNative {
  // Phase 1
  generateKeypair(): Promise<KeyPair>;
  importFromMnemonic(words: string[]): Promise<KeyPair>;
  // Phase 2
  initCore(privateKeyHex: string, dbDir: string): Promise<void>;
  // Network
  initNetwork(relayUrl: string | null): Promise<string>;
  isNetworkInitialized(): Promise<boolean>;
  getNodeId(): Promise<string>;
  createOrUpdateProfile(username: string, bio: string | null, availableFor: string[], isPublic: boolean, avatarBlobId: string | null, emailEnabled: boolean): Promise<void>;
  getPkarrUrl(publicKeyHex: string): string;
  getPkarrUrlFromZ32(z32Key: string): string;
  resolvePkarr(z32Key: string): Promise<PkarrResolved | null>;
  getMyProfile(): Promise<Profile | null>;
  getProfile(publicKey: string): Promise<Profile | null>;
  createOrg(name: string, typeLabel: string, description: string | null, isPublic: boolean): Promise<string>;
  listMyOrgs(): Promise<OrgSummary[]>;
  updateOrg(orgId: string, name: string | null, typeLabel: string | null, description: string | null, avatarBlobId: string | null, coverBlobId: string | null, welcomeText: string | null, customEmojiJson: string | null, orgCooldownSecs: number | null, isPublic: boolean | null, emailEnabled: boolean | null): Promise<string>; // returns base64 op bytes
  createRoom(orgId: string, name: string): Promise<string>;
  listRooms(orgId: string, includeArchived: boolean): Promise<Room[]>;
  updateRoom(orgId: string, roomId: string, name: string | null, roomCooldownSecs: number | null): Promise<void>;
  setRoomCooldown(orgId: string, roomId: string, cooldownSecs: number): Promise<void>;
  deleteRoom(orgId: string, roomId: string): Promise<void>;
  archiveRoom(orgId: string, roomId: string): Promise<void>;
  unarchiveRoom(orgId: string, roomId: string): Promise<void>;
  createEvent(
    orgId: string,
    title: string,
    description: string | null,
    locationType: string,
    locationText: string | null,
    locationRoomId: string | null,
    startAt: number,
    endAt: number | null,
  ): Promise<{ id: string; opBytesBase64: string }>;
  updateEvent(
    orgId: string,
    eventId: string,
    title: string | null,
    description: string | null,
    locationType: string | null,
    locationText: string | null,
    locationRoomId: string | null,
    startAt: number | null,
    endAt: number | null,
  ): Promise<string>; // returns base64 op bytes
  deleteEvent(orgId: string, eventId: string): Promise<string>; // returns base64 op bytes
  listEvents(orgId: string): Promise<Event[]>;
  setEventRsvp(eventId: string, status: string): Promise<string>; // returns base64 op bytes
  clearEventRsvp(eventId: string): Promise<string>; // returns base64 op bytes
  listEventRsvps(eventId: string): Promise<EventRsvp[]>;
  sendMessage(
    roomId: string | null,
    dmThreadId: string | null,
    contentType: string,
    textContent: string | null,
    blobId: string | null,
    embedUrl: string | null,
    mentions: string[],
    replyTo: string | null,
  ): Promise<{ id: string; opBytesBase64: string }>;
  listMessages(
    roomId: string | null,
    dmThreadId: string | null,
    limit: number,
    beforeTimestamp: number | null,
  ): Promise<Message[]>;
  addReaction(messageId: string, emoji: string): Promise<{ id: string; opBytesBase64: string }>;
  removeReaction(messageId: string, emoji: string): Promise<{ id: string; opBytesBase64: string }>;
  listReactions(messageIds: string[]): Promise<Reaction[]>;
  deleteMessage(messageId: string, orgId: string | null): Promise<{ id: string; opBytesBase64: string }>;
  createDmThread(recipientKey: string): Promise<{ id: string; opBytesBase64: string }>;
  listDmThreads(): Promise<DmThread[]>;
  acceptMessageRequest(threadId: string): Promise<void>;
  declineMessageRequest(threadId: string): Promise<void>;
  // Phase 3
  getConnectionStatus(): Promise<ConnectionStatus>;
  searchPublicOrgs(query: string): Promise<OrgSummary[]>;
  // Phase 5
  generateInviteToken(orgId: string, accessLevel: string, expiryTimestamp: number): string;
  verifyInviteToken(tokenBase64: string, currentTimestamp: number): InviteTokenInfo;
  addMemberDirect(orgId: string, memberPublicKey: string, accessLevel: string): Promise<void>;
  removeMemberFromOrg(orgId: string, memberPublicKey: string): Promise<void>;
  changeMemberPermission(orgId: string, memberPublicKey: string, newAccessLevel: string): Promise<void>;
  listOrgMembers(orgId: string): Promise<MemberInfo[]>;
  setUserCooldown(orgId: string, memberPublicKey: string, cooldownSecs: number): Promise<void>;
  iceMember(orgId: string, memberPublicKey: string, durationSecs: number): Promise<void>;
  uniceMember(orgId: string, memberPublicKey: string): Promise<void>;
  listIcedMembers(orgId: string): Promise<IceInfo[]>;
  setOrgCooldown(orgId: string, cooldownSecs: number): Promise<void>;
  deleteOrg(orgId: string): Promise<void>;
  // Member moderation (stubs)
  kickMember(orgId: string, memberPublicKey: string): Promise<void>;
  banMember(orgId: string, memberPublicKey: string): Promise<void>;
  unbanMember(orgId: string, memberPublicKey: string): Promise<void>;
  muteMember(orgId: string, memberPublicKey: string, durationSeconds: number): Promise<void>;
  unmuteMember(orgId: string, memberPublicKey: string): Promise<void>;
  ignoreUser(publicKey: string): Promise<void>;
  unignoreUser(publicKey: string): Promise<void>;
  listIgnoredUsers(): Promise<string[]>;
  // Phase 7 — binary data is base64-encoded over the RN bridge
  prepareOutboundEmail(
    to: string,
    subject: string,
    bodyText: string,
    bodyHtml: string | null,
    replyToMessageId: string | null,
  ): Promise<string>; // returns JSON: { signed_payload: string, signature: string }
  uploadBlob(dataBase64: string, mimeType: string, roomId: string | null): Promise<string>;
  getBlob(blobHash: string, roomId: string | null): Promise<string>; // returns base64
  hasBlob(blobHash: string): Promise<boolean>;
  requestBlobFromPeer(blobHash: string, peerPublicKey: string, timeoutSecs: number): Promise<string | null>; // returns base64 or null
  provideBlobToPeer(blobHash: string, peerPublicKey: string): Promise<void>;
  // Sync — receive op from TopicDO WebSocket
  ingestOpFfi(topicHex: string, seq: number, opBytesBase64: string): Promise<void>;
  getTopicSeqFfi(topicHex: string): Promise<number>;
  // Onion routing — bytes are base64-encoded over the RN bridge
  buildOnionPacket(hops: OnionHopFfi[], topicIdBase64: string, opBase64: string): Promise<string>; // returns base64
  peelOnionLayer(packetBase64: string, recipientSeedHex: string): Promise<{
    peelType: string;
    nextHopUrl: string | null;
    innerPacketBase64: string | null;
    topicIdBase64: string | null;
    opBase64: string | null;
  }>;
}

function loadNative(): GardensCoreNative {
  try {
    // Prefer TurboModule if available, fallback to legacy NativeModules
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const turbo = (TurboModuleRegistry as any)?.get?.('GardensCore');
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const legacy = (NativeModules as any)?.GardensCore;
    const mod = (turbo || legacy) as GardensCoreNative | undefined;
    if (mod) {
      return mod;
    }
    throw new Error('GardensCore native module not loaded');
  } catch {
    return {
      async generateKeypair(): Promise<KeyPair> {
        throw new Error('gardens_core native module not loaded');
      },
      async importFromMnemonic(_words: string[]): Promise<KeyPair> {
        throw new Error('gardens_core native module not loaded');
      },
      async initCore() { throw new Error('gardens_core native module not loaded'); },
      async initNetwork() { throw new Error('gardens_core native module not loaded'); },
      async isNetworkInitialized() { return false; },
      async getNodeId() { throw new Error('gardens_core native module not loaded'); },
      async createOrUpdateProfile(_u: string, _b: string | null, _a: string[], _p: boolean, _av: string | null, _em: boolean) { throw new Error('gardens_core not loaded'); },
      getPkarrUrl() { throw new Error('gardens_core not loaded'); },
      getPkarrUrlFromZ32() { throw new Error('gardens_core not loaded'); },
      async resolvePkarr() { return null; },
      async getMyProfile() { return null; },
      async getProfile() { return null; },
      async createOrg() { throw new Error('gardens_core not loaded'); },
      async listMyOrgs() { return []; },
      async updateOrg() { throw new Error('gardens_core not loaded'); },
      async createRoom() { throw new Error('gardens_core not loaded'); },
      async listRooms() { return []; },
      async updateRoom() { throw new Error('gardens_core not loaded'); },
      async setRoomCooldown() { throw new Error('gardens_core not loaded'); },
      async deleteRoom() { throw new Error('gardens_core not loaded'); },
      async archiveRoom() { throw new Error('gardens_core not loaded'); },
      async unarchiveRoom() { throw new Error('gardens_core not loaded'); },
      async createEvent() { throw new Error('gardens_core not loaded'); },
      async updateEvent() { throw new Error('gardens_core not loaded'); },
      async deleteEvent() { throw new Error('gardens_core not loaded'); },
      async listEvents() { return []; },
      async setEventRsvp() { throw new Error('gardens_core not loaded'); },
      async clearEventRsvp() { throw new Error('gardens_core not loaded'); },
      async listEventRsvps() { return []; },
      async sendMessage() { throw new Error('gardens_core not loaded'); },
      async listMessages() { return []; },
      async addReaction() { throw new Error('gardens_core not loaded'); },
      async removeReaction() { throw new Error('gardens_core not loaded'); },
      async listReactions() { return []; },
      async deleteMessage() { throw new Error('gardens_core not loaded'); },
      async createDmThread() { throw new Error('gardens_core not loaded'); },
      async listDmThreads() { return []; },
      async acceptMessageRequest() { throw new Error('gardens_core not loaded'); },
      async declineMessageRequest() { throw new Error('gardens_core not loaded'); },
      async getConnectionStatus() { return 'Offline'; },
      async searchPublicOrgs() { return []; },
      generateInviteToken() { throw new Error('gardens_core not loaded'); },
      verifyInviteToken() { throw new Error('gardens_core not loaded'); },
      async addMemberDirect() { throw new Error('gardens_core not loaded'); },
      async removeMemberFromOrg() { throw new Error('gardens_core not loaded'); },
      async changeMemberPermission() { throw new Error('gardens_core not loaded'); },
      async listOrgMembers() { return []; },
      async setUserCooldown() { throw new Error('gardens_core not loaded'); },
      async iceMember() { throw new Error('gardens_core not loaded'); },
      async uniceMember() { throw new Error('gardens_core not loaded'); },
      async listIcedMembers() { return []; },
      async setOrgCooldown() { throw new Error('gardens_core not loaded'); },
      async deleteOrg() { throw new Error('gardens_core not loaded'); },
      async kickMember() { throw new Error('gardens_core not loaded'); },
      async banMember() { throw new Error('gardens_core not loaded'); },
      async unbanMember() { throw new Error('gardens_core not loaded'); },
      async muteMember() { throw new Error('gardens_core not loaded'); },
      async unmuteMember() { throw new Error('gardens_core not loaded'); },
      async ignoreUser() { throw new Error('gardens_core not loaded'); },
      async unignoreUser() { throw new Error('gardens_core not loaded'); },
      async listIgnoredUsers() { return []; },
      async uploadBlob() { throw new Error('gardens_core not loaded'); },
      async getBlob() { throw new Error('gardens_core not loaded'); },
      async hasBlob() { return false; },
      async requestBlobFromPeer() { return null; },
      async provideBlobToPeer() { throw new Error('gardens_core not loaded'); },
      async ingestOpFfi() { throw new Error('gardens_core not loaded'); },
      async getTopicSeqFfi() { return 0; },
      async buildOnionPacket() { throw new Error('gardens_core not loaded'); },
      async peelOnionLayer() { throw new Error('gardens_core not loaded'); },
      async prepareOutboundEmail() { throw new Error('gardens_core not loaded'); },
    };
  }
}

const native = loadNative();

// ── Phase 1 exports ───────────────────────────────────────────────────────────

/** Generate a fresh Ed25519 keypair and 24-word BIP-39 mnemonic. */
export async function generateKeypair(): Promise<KeyPair> {
  return native.generateKeypair();
}

/**
 * Re-derive a keypair from an existing 24-word mnemonic.
 * Throws {@link KeyError} if the mnemonic is invalid.
 */
export async function importFromMnemonic(words: string[]): Promise<KeyPair> {
  try {
    return await native.importFromMnemonic(words);
  } catch (err: unknown) {
    if (err instanceof Error && err.message.includes('InvalidMnemonic')) {
      throw new KeyError('InvalidMnemonic', err.message);
    }
    throw err;
  }
}

// ── Phase 2/Profile exports ───────────────────────────────────────────────────

export async function createOrUpdateProfile(
  username: string,
  bio: string | null,
  availableFor: string[],
  isPublic: boolean = false,
  avatarBlobId: string | null = null,
  emailEnabled: boolean = false,
): Promise<void> {
  return native.createOrUpdateProfile(username, bio, availableFor, isPublic, avatarBlobId, emailEnabled);
}

export function getPkarrUrl(publicKeyHex: string): string {
  try {
    return native.getPkarrUrl(publicKeyHex);
  } catch (err: unknown) {
    if (err instanceof Error) {
      throw new Error(`Failed to get pkarr URL: ${err.message}`);
    }
    throw err;
  }
}

/// Get pkarr URL from a z32-encoded public key (for orgs).
/// Input: z32-encoded key (e.g., "yj4bqhvahk8dge...")
/// Returns: `pk:<z32-encoded-pubkey>`
export function getPkarrUrlFromZ32(z32Key: string): string {
  try {
    return native.getPkarrUrlFromZ32(z32Key);
  } catch (err: unknown) {
    if (err instanceof Error) {
      throw new Error(`Failed to get pkarr URL from z32: ${err.message}`);
    }
    throw err;
  }
}

export async function resolvePkarr(z32Key: string): Promise<PkarrResolved | null> {
  return native.resolvePkarr(z32Key);
}

export async function getMyProfile(): Promise<Profile | null> {
  return native.getMyProfile();
}

export async function getProfile(publicKey: string): Promise<Profile | null> {
  return native.getProfile(publicKey);
}

// ── Phase 2/Orgs/Rooms/DMs exports (wrappers over native) ─────────────────────

export async function createOrg(
  name: string,
  typeLabel: string,
  description: string | null,
  isPublic: boolean,
): Promise<string> {
  return native.createOrg(name, typeLabel, description, isPublic);
}

export async function listMyOrgs(): Promise<OrgSummary[]> {
  return native.listMyOrgs();
}

export async function updateOrg(
  orgId: string,
  name: string | null = null,
  typeLabel: string | null = null,
  description: string | null = null,
  avatarBlobId: string | null = null,
  coverBlobId: string | null = null,
  welcomeText: string | null = null,
  customEmojiJson: string | null = null,
  orgCooldownSecs: number | null = null,
  isPublic: boolean | null = null,
  emailEnabled: boolean | null = null,
): Promise<SendResult> {
  const opBytesBase64 = await native.updateOrg(orgId, name, typeLabel, description, avatarBlobId, coverBlobId, welcomeText, customEmojiJson, orgCooldownSecs, isPublic, emailEnabled);
  return { id: orgId, opBytes: base64ToBytes(opBytesBase64) };
}

export async function createRoom(orgId: string, name: string): Promise<string> {
  return native.createRoom(orgId, name);
}

export async function listRooms(orgId: string, includeArchived: boolean = false): Promise<Room[]> {
  return native.listRooms(orgId, includeArchived);
}

export async function updateRoom(
  orgId: string,
  roomId: string,
  name: string | null = null,
  roomCooldownSecs: number | null = null,
): Promise<void> {
  return native.updateRoom(orgId, roomId, name, roomCooldownSecs);
}

export async function setRoomCooldown(orgId: string, roomId: string, cooldownSecs: number): Promise<void> {
  return native.setRoomCooldown(orgId, roomId, cooldownSecs);
}

export async function deleteRoom(orgId: string, roomId: string): Promise<void> {
  return native.deleteRoom(orgId, roomId);
}

export async function archiveRoom(orgId: string, roomId: string): Promise<void> {
  return native.archiveRoom(orgId, roomId);
}

export async function unarchiveRoom(orgId: string, roomId: string): Promise<void> {
  return native.unarchiveRoom(orgId, roomId);
}

export async function createEvent(
  orgId: string,
  title: string,
  description: string | null,
  locationType: string,
  locationText: string | null,
  locationRoomId: string | null,
  startAt: number,
  endAt: number | null,
): Promise<SendResult> {
  const raw = await native.createEvent(orgId, title, description, locationType, locationText, locationRoomId, startAt, endAt);
  return { id: raw.id, opBytes: base64ToBytes(raw.opBytesBase64) };
}

export async function updateEvent(
  orgId: string,
  eventId: string,
  title: string | null = null,
  description: string | null = null,
  locationType: string | null = null,
  locationText: string | null = null,
  locationRoomId: string | null = null,
  startAt: number | null = null,
  endAt: number | null = null,
): Promise<SendResult> {
  const opBytesBase64 = await native.updateEvent(orgId, eventId, title, description, locationType, locationText, locationRoomId, startAt, endAt);
  return { id: eventId, opBytes: base64ToBytes(opBytesBase64) };
}

export async function deleteEvent(orgId: string, eventId: string): Promise<SendResult> {
  const opBytesBase64 = await native.deleteEvent(orgId, eventId);
  return { id: eventId, opBytes: base64ToBytes(opBytesBase64) };
}

export async function listEvents(orgId: string): Promise<Event[]> {
  return native.listEvents(orgId);
}

export async function setEventRsvp(eventId: string, status: string): Promise<SendResult> {
  const opBytesBase64 = await native.setEventRsvp(eventId, status);
  return { id: eventId, opBytes: base64ToBytes(opBytesBase64) };
}

export async function clearEventRsvp(eventId: string): Promise<SendResult> {
  const opBytesBase64 = await native.clearEventRsvp(eventId);
  return { id: eventId, opBytes: base64ToBytes(opBytesBase64) };
}

export async function listEventRsvps(eventId: string): Promise<EventRsvp[]> {
  return native.listEventRsvps(eventId);
}

export async function sendMessage(
  roomId: string | null,
  dmThreadId: string | null,
  contentType: string,
  textContent: string | null,
  blobId: string | null,
  embedUrl: string | null,
  mentions: string[],
  replyTo: string | null,
): Promise<SendResult> {
  const raw = await native.sendMessage(roomId, dmThreadId, contentType, textContent, blobId, embedUrl, mentions, replyTo);
  return { id: raw.id, opBytes: base64ToBytes(raw.opBytesBase64) };
}

export async function listMessages(
  roomId: string | null,
  dmThreadId: string | null,
  limit: number,
  beforeTimestamp: number | null,
): Promise<Message[]> {
  return native.listMessages(roomId, dmThreadId, limit, beforeTimestamp);
}

export async function addReaction(messageId: string, emoji: string): Promise<{ id: string; opBytesBase64: string }> {
  return native.addReaction(messageId, emoji);
}

export async function removeReaction(messageId: string, emoji: string): Promise<{ id: string; opBytesBase64: string }> {
  return native.removeReaction(messageId, emoji);
}

export async function listReactions(messageIds: string[]): Promise<Reaction[]> {
  if (typeof (native as { listReactions?: unknown }).listReactions !== 'function') {
    // Older native modules may not implement reactions yet.
    return [];
  }
  return native.listReactions(messageIds);
}

export async function deleteMessage(messageId: string, orgId?: string): Promise<SendResult> {
  const raw = await native.deleteMessage(messageId, orgId ?? null);
  return { id: raw.id, opBytes: base64ToBytes(raw.opBytesBase64) };
}

export async function createDmThread(recipientKey: string): Promise<SendResult> {
  const raw = await native.createDmThread(recipientKey);
  return { id: raw.id, opBytes: base64ToBytes(raw.opBytesBase64) };
}

export async function listDmThreads(): Promise<DmThread[]> {
  return native.listDmThreads();
}

export async function acceptMessageRequest(threadId: string): Promise<void> {
  return native.acceptMessageRequest(threadId);
}

export async function declineMessageRequest(threadId: string): Promise<void> {
  return native.declineMessageRequest(threadId);
}

// ── Phase 3 exports ───────────────────────────────────────────────────────────

export async function initCore(privateKeyHex: string): Promise<void> {
  return native.initCore(privateKeyHex, '');
}

export async function initNetwork(relayUrl: string | null = null): Promise<string> {
  return native.initNetwork(relayUrl);
}

export async function isNetworkInitialized(): Promise<boolean> {
  return native.isNetworkInitialized();
}

export async function getNodeId(): Promise<string> {
  return native.getNodeId();
}

export async function getConnectionStatus(): Promise<ConnectionStatus> {
  return native.getConnectionStatus();
}

export async function searchPublicOrgs(query: string): Promise<OrgSummary[]> {
  return native.searchPublicOrgs(query);
}

// ── Phase 5 exports ───────────────────────────────────────────────────────────

export function generateInviteToken(
  orgId: string,
  accessLevel: string,
  expiryTimestamp: number,
): string {
  try {
    return native.generateInviteToken(orgId, accessLevel, expiryTimestamp);
  } catch (err: unknown) {
    if (err instanceof Error && err.message.includes('Unauthorized')) {
      throw new AuthError('Unauthorized', err.message);
    }
    throw err;
  }
}

export function verifyInviteToken(
  tokenBase64: string,
  currentTimestamp: number,
): InviteTokenInfo {
  try {
    return native.verifyInviteToken(tokenBase64, currentTimestamp);
  } catch (err: unknown) {
    if (err instanceof Error) {
      if (err.message.includes('InvalidSignature')) {
        throw new AuthError('InvalidSignature', err.message);
      }
      if (err.message.includes('TokenExpired')) {
        throw new AuthError('TokenExpired', err.message);
      }
    }
    throw err;
  }
}

export async function addMemberDirect(
  orgId: string,
  memberPublicKey: string,
  accessLevel: string,
): Promise<void> {
  return native.addMemberDirect(orgId, memberPublicKey, accessLevel);
}

export async function removeMemberFromOrg(
  orgId: string,
  memberPublicKey: string,
): Promise<void> {
  return native.removeMemberFromOrg(orgId, memberPublicKey);
}

export async function changeMemberPermission(
  orgId: string,
  memberPublicKey: string,
  newAccessLevel: string,
): Promise<void> {
  return native.changeMemberPermission(orgId, memberPublicKey, newAccessLevel);
}

export async function listOrgMembers(orgId: string): Promise<MemberInfo[]> {
  return native.listOrgMembers(orgId);
}

export async function setUserCooldown(orgId: string, memberPublicKey: string, cooldownSecs: number): Promise<void> {
  return native.setUserCooldown(orgId, memberPublicKey, cooldownSecs);
}

export async function iceMember(orgId: string, memberPublicKey: string, durationSecs: number): Promise<void> {
  return native.iceMember(orgId, memberPublicKey, durationSecs);
}

export async function uniceMember(orgId: string, memberPublicKey: string): Promise<void> {
  return native.uniceMember(orgId, memberPublicKey);
}

export async function listIcedMembers(orgId: string): Promise<IceInfo[]> {
  return native.listIcedMembers(orgId);
}

export async function setOrgCooldown(orgId: string, cooldownSecs: number): Promise<void> {
  return native.setOrgCooldown(orgId, cooldownSecs);
}

export async function deleteOrg(orgId: string): Promise<void> {
  return native.deleteOrg(orgId);
}

// Member moderation (stubs)
export async function kickMember(orgId: string, memberPublicKey: string): Promise<void> {
  return native.kickMember(orgId, memberPublicKey);
}

export async function banMember(orgId: string, memberPublicKey: string): Promise<void> {
  return native.banMember(orgId, memberPublicKey);
}

export async function unbanMember(orgId: string, memberPublicKey: string): Promise<void> {
  return native.unbanMember(orgId, memberPublicKey);
}

export async function muteMember(orgId: string, memberPublicKey: string, durationSeconds: number): Promise<void> {
  return native.muteMember(orgId, memberPublicKey, durationSeconds);
}

export async function unmuteMember(orgId: string, memberPublicKey: string): Promise<void> {
  return native.unmuteMember(orgId, memberPublicKey);
}

export async function ignoreUser(publicKey: string): Promise<void> {
  return native.ignoreUser(publicKey);
}

export async function unignoreUser(publicKey: string): Promise<void> {
  return native.unignoreUser(publicKey);
}

export async function listIgnoredUsers(): Promise<string[]> {
  return native.listIgnoredUsers();
}

// ── Phase 7: Blobs ────────────────────────────────────────────────────────────

export class BlobError extends Error {
  constructor(
    public readonly kind: 'NotInitialized' | 'NotFound' | 'StoreError' | 'IoError',
    message: string,
  ) {
    super(message);
    this.name = 'BlobError';
  }
}

export async function uploadBlob(
  data: Uint8Array,
  mimeType: string,
  roomId: string | null,
): Promise<string> {
  let binary = '';
  for (let i = 0; i < data.byteLength; i++) { binary += String.fromCharCode(data[i]); }
  return native.uploadBlob(btoa(binary), mimeType, roomId);
}

export async function getBlob(blobHash: string, roomId: string | null): Promise<Uint8Array> {
  const base64 = await native.getBlob(blobHash, roomId);
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) { bytes[i] = binary.charCodeAt(i); }
  return bytes;
}

export async function hasBlob(blobHash: string): Promise<boolean> {
  return native.hasBlob(blobHash);
}

export async function requestBlobFromPeer(
  blobHash: string,
  peerPublicKey: string,
  timeoutSecs: number = 30,
): Promise<Uint8Array | null> {
  const base64 = await native.requestBlobFromPeer(blobHash, peerPublicKey, timeoutSecs);
  if (!base64) return null;
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) { bytes[i] = binary.charCodeAt(i); }
  return bytes;
}

export async function provideBlobToPeer(
  blobHash: string,
  peerPublicKey: string,
): Promise<void> {
  return native.provideBlobToPeer(blobHash, peerPublicKey);
}

// ── Onion routing ─────────────────────────────────────────────────────────────

function bytesToBase64(bytes: Uint8Array): string {
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) { binary += String.fromCharCode(bytes[i]); }
  return btoa(binary);
}

function base64ToBytes(base64: string): Uint8Array {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) { bytes[i] = binary.charCodeAt(i); }
  return bytes;
}

// ── Sync ─────────────────────────────────────────────────────────────────────

export async function ingestOp(topicHex: string, seq: number, opBytes: Uint8Array): Promise<void> {
  return native.ingestOpFfi(topicHex, seq, bytesToBase64(opBytes));
}

export async function getTopicSeq(topicHex: string): Promise<number> {
  return native.getTopicSeqFfi(topicHex);
}

// ── Onion routing ─────────────────────────────────────────────────────────────

export async function buildOnionPacket(
  hops: OnionHopFfi[],
  topicId: Uint8Array,
  op: Uint8Array,
): Promise<Uint8Array> {
  const base64 = await native.buildOnionPacket(hops, bytesToBase64(topicId), bytesToBase64(op));
  return base64ToBytes(base64);
}

export async function peelOnionLayer(
  packet: Uint8Array,
  recipientSeedHex: string,
): Promise<OnionPeeled> {
  const raw = await native.peelOnionLayer(bytesToBase64(packet), recipientSeedHex);
  return {
    peelType: raw.peelType as 'forward' | 'deliver',
    nextHopUrl: raw.nextHopUrl,
    innerPacket: raw.innerPacketBase64 ? base64ToBytes(raw.innerPacketBase64) : null,
    topicId: raw.topicIdBase64 ? base64ToBytes(raw.topicIdBase64) : null,
    op: raw.opBase64 ? base64ToBytes(raw.opBase64) : null,
  };
}

// ── Email ─────────────────────────────────────────────────────────────────────

export async function prepareOutboundEmail(params: {
  to: string;
  subject: string;
  bodyText: string;
  bodyHtml?: string;
  replyToMessageId?: string;
}): Promise<{ signedPayload: string; signature: string }> {
  const raw = await native.prepareOutboundEmail(
    params.to,
    params.subject,
    params.bodyText,
    params.bodyHtml ?? null,
    params.replyToMessageId ?? null,
  );
  const parsed = JSON.parse(raw) as { signed_payload: string; signature: string };
  return { signedPayload: parsed.signed_payload, signature: parsed.signature };
}
